In [31]:
#import numpy as np
#filename = 'CMS32_DESC_LONG_DX_subset.txt'
#data = np.loadtxt(filename, delimiter='|', dtype=str)
#data.shape

In [ ]:
#import csv
#file = open("unisex_names_table.csv")
#csvreader = csv.reader(file)
#airline_safety = list(csvreader)
#print(airline_safety)

![Pandas Selections and Indexing ](http://104.236.88.249/wp-content/uploads/2016/10/Pandas-selections-and-indexing.png)

###  Single selections using iloc and DataFrame

In [ ]:

# Single selections using iloc and DataFrame

# Rows:

data.iloc[0] # first row of data frame (Aleshia Tomkiewicz) - Note a Series data type output.

data.iloc[1] # second row of data frame (Evan Zigomalas)

data.iloc[-1] # last row of data frame (Mi Richan)

# Columns:

data.iloc[:,0] # first column of data frame (first_name)

data.iloc[:,1] # second column of data frame (last_name)

data.iloc[:,-1] # last column of data frame (id)

### Multiple columns and rows can be selected together using the .iloc indexer.

In [ ]:
# Multiple row and column selections using iloc and DataFrame

data.iloc[0:5] # first five rows of dataframe

data.iloc[:, 0:2] # first two columns of data frame with all rows

data.iloc[[0,3,6,24], [0,5,6]] # 1st, 4th, 7th, 25th row + 1st 6th 7th columns.

data.iloc[0:5, 5:8] # first 5 rows and 5th, 6th, 7th columns of data frame (county -> phone1).

### List operations

In [12]:
>>> l2 = [1, 2, 3]
>>> l1 = [4, 5, 6]


In [19]:
#l4=[]
l4=l4+l2
l4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

### Use names parameter
df = pd.read_csv(file_path, usecols=[3,6], names=['colA', 'colB'])
or use header=None to explicitly tells people that the csv has no headers (anyway both lines are identical)
df = pd.read_csv(file_path, usecols=[3,6], names=['colA', 'colB'], header=None)
So that you can retrieve your data by 
### with `names` parameter
df['colA']
df['colB'] 
instead of 
### without `names` parameter
df[0]
df[1]
### Use nrows parameter
to import top 50 rows: nrows=50

In [29]:
import pandas as pd
filename = '~/Documents/NLP/CMS32_DESC_LONG_DX_subset.txt'
df = pd.read_csv(filename, header=None, delimiter='|', dtype=str, nrows=100)
df.shape
#print(df)

(100, 2)

In [30]:
df1 = df[df[0].str.contains("363")]
print(df1)

        0                                                  1
67  36300                 Focal chorioretinitis, unspecified
68  36301  Focal choroiditis and chorioretinitis, juxtapa...
69  36303  Focal choroiditis and chorioretinitis of other...
70  36304  Focal choroiditis and chorioretinitis, peripheral
71  36305  Focal retinitis and retinochoroiditis, juxtapa...
72  36306  Focal retinitis and retinochoroiditis, macular...
73  36307  Focal retinitis and retinochoroiditis of other...
74  36308  Focal retinitis and retinochoroiditis, peripheral
75  36310          Disseminated chorioretinitis, unspecified
76  36311  Disseminated choroiditis and chorioretinitis, ...
77  36312  Disseminated choroiditis and chorioretinitis, ...
78  36313  Disseminated choroiditis and chorioretinitis, ...
79  36314  Disseminated retinitis and retinochoroiditis, ...
80  36315  Disseminated retinitis and retinochoroiditis, ...
81  36320                       Chorioretinitis, unspecified
82  36321               

In [31]:
df1=df1.values

In [32]:
>>> from sklearn.feature_extraction.text import CountVectorizer
>>> from sklearn.feature_extraction import stop_words

In [33]:
>>> vectorizer = CountVectorizer(stop_words=stop_words.ENGLISH_STOP_WORDS)
>>> vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None,
        stop_words=frozenset({'hundred', 'therefore', 'their', 'un', 'thin', 'third', 'whence', 'an', 'hers', 'who', 'after', 'all', 'within', 'yourself', 'fifteen', 'perhaps', 'namely', 'than', 'noone', 'six', 'more', 'always', 'whither', 'due', 'amoungst', 'below', 'interest', 'why', 'even', 'call', 'else...im', 'wherein', 'out', 'done', 'wherever', 'well', 'sixty', 'we', 'many', 'those', 'she', 'itself'}),
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [34]:
#>>> t,z = data[:,0], data[:,3] 
>>> corpus = df1[:,1]
>>> X = vectorizer.fit_transform(corpus)
>>> X

<33x42 sparse matrix of type '<class 'numpy.int64'>'
	with 114 stored elements in Compressed Sparse Row format>

In [35]:
>>> vectorizer.get_feature_names()

['angioid',
 'atrophy',
 'central',
 'chorioretinal',
 'chorioretinitis',
 'choroid',
 'choroidal',
 'choroideremia',
 'choroiditis',
 'circumpapillary',
 'degeneration',
 'diffuse',
 'disease',
 'disseminated',
 'dystrophy',
 'epitheliopathy',
 'focal',
 'generalized',
 'harada',
 'hereditary',
 'juxtapapillary',
 'macular',
 'metastatic',
 'paramacular',
 'pars',
 'partial',
 'peripheral',
 'pigment',
 'planitis',
 'pole',
 'posterior',
 'retinitis',
 'retinochoroiditis',
 'retinopathy',
 'scar',
 'scars',
 'secondary',
 'senile',
 'solar',
 'streaks',
 'total',
 'unspecified']

In [36]:
>>> X.toarray()

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

Hence words that were not seen in the training corpus will be completely ignored in future calls to the transform method:

In [37]:
>>> vectorizer.transform(['Something completely diabetic.']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

As tf–idf is very often used for text features, there is also another class called TfidfVectorizer that combines all the options of CountVectorizer and TfidfTransformer in a single model:

In [20]:
>>> from sklearn.feature_extraction.text import TfidfVectorizer
>>> vectorizer_t = TfidfVectorizer(stop_words=stop_words.ENGLISH_STOP_WORDS)
>>> vectorizer_t.fit_transform(corpus).toarray()

array([[0.80173655, 0.45973138, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.3819235 , 0.        , 0.        ],
       [0.        , 0.41174171, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.84466947, 0.34205591, 0.        , 0.        ],
       [0.        , 0.35947373, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.48761927, 0.73744407,
        0.        , 0.2986341 , 0.        , 0.        ],
       [0.        , 0.35947373, 0.        , 0.        , 0.        ,
        0.        , 0.73744407, 0.        , 0.48761927, 0.        ,
        0.        , 0.2986341 , 0.        , 0.        ],
       [0.        , 0.35947373, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.73744407, 0.48761927, 0.        ,
        0.        , 0.2986341 , 0.        , 0.        ],
       [0.        , 0.35947373, 0. 

In [21]:
>>> vectorizer_t.transform(['Something completely diabetic.']).toarray()

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])